version: 0.0
Resources:
  - myEKSApp:
      Type: AWS::EKS::Application
      Properties:
        ClusterName: brain-task-App
        Namespace: default

hooks:
  BeforeInstall:
    - location: scripts/cleanup.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 600
      runas: root

