version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 323997748732.dkr.ecr.ap-south-1.amazonaws.com

  build:
    commands:
      - echo Build started on `date`
      - echo Building Docker image...
      - docker build -t brain-task-app .
      - docker tag brain-task-app:latest 323997748732.dkr.ecr.ap-south-1.amazonaws.com/brain-task-app:latest

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing Docker image to ECR...
      - docker push 323997748732.dkr.ecr.ap-south-1.amazonaws.com/brain-task-app:latest
      - echo Writing image definitions file...
      - printf '[{"name":"brain-task-container","imageUri":"323997748732.dkr.ecr.ap-south-1.amazonaws.com/brain-task-app:latest"}]' > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
    - deployment.yaml
    - service.yaml
    - scripts/**/*
